name: nightly-sericea-build

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main # Checkout the main branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:nvidia

      - name: Build and push non-nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./non-nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:non-nvidia
