name: sericea-build-pr

on:
  pull_request:
permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }} # fetch base branch

      - name: Check for changes in Nvidia Dockerfile
        id: check_changes_nvidia
        run: |
          MODIFIED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep 'nvidia/Dockerfile' || echo "")
          echo "::set-output name=modified::${MODIFIED}"

      - name: Check for changes in Non-Nvidia Dockerfile
        id: check_changes_non_nvidia
        run: |
          MODIFIED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep 'non-nvidia/Dockerfile' || echo "")
          echo "::set-output name=modified::${MODIFIED}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.check_changes_nvidia.outputs.modified == 'nvidia/Dockerfile' || steps.check_changes_non_nvidia.outputs.modified == 'non-nvidia/Dockerfile'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_changes_nvidia.outputs.modified == 'nvidia/Dockerfile' || steps.check_changes_non_nvidia.outputs.modified == 'non-nvidia/Dockerfile'

      - name: Build and push nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:nvidia
        if: steps.check_changes_nvidia.outputs.modified == 'nvidia/Dockerfile'

      - name: Build and push non-nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./non-nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:non-nvidia
        if: steps.check_changes_non_nvidia.outputs.modified == 'non-nvidia/Dockerfile'

      - name: Dockerfile not modified
        if: steps.check_changes_nvidia.outputs.modified != 'nvidia/Dockerfile' && steps.check_changes_non_nvidia.outputs.modified != 'non-nvidia/Dockerfile'
        run: echo "Dockerfile was not modified in this PR."

      - name: Block merge if build fails
        if: failure()
        run: exit 1
