name: sericea-build-pr

on:
  pull_request:
permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_modified: ${{ steps.check_changes.outputs.modified }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in Dockerfile
        id: check_changes
        run: |
          git fetch origin ${{ github.base_ref }} # fetch base branch
          MODIFIED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep 'Dockerfile' || echo "")
          echo "::set-output name=modified::${MODIFIED}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.check_changes.outputs.modified == 'Dockerfile'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_changes.outputs.modified == 'Dockerfile'

      - name: Build and push nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:nvidia
        if: steps.check_changes.outputs.modified == 'Dockerfile' && startsWith(steps.check_changes.outputs.modified, 'nvidia')

      - name: Build and push non-nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./non-nvidia
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:non-nvidia
        if: steps.check_changes.outputs.modified == 'Dockerfile' && startsWith(steps.check_changes.outputs.modified, 'non-nvidia')

      - name: Dockerfile not modified
        if: steps.check_changes.outputs.modified != 'Dockerfile'
        run: echo "Dockerfile was not modified in this PR."

      - name: Block merge if build fails
        if: failure()
        run: exit 1
